### ISSUE TITLE
Getting started with dxvk-native

### ISSUE THREAD

**Issue by Arxcis** [Joshua-Ashton/dxvk-native#1]
Hey @Joshua-Ashton. Since building with `dxvk-native` may be quite different than with `dxvk`, I figured it will need it's own Getting started - guide. Can you possibly answer some or all of the questions below? I will try to figure out the rest :dancer: 

## Use case (Correct me if I am wrong)
As a developer I want to use `dxvk-native` to compile and run my DirectX-engine natively on Linux. (Not inside Wine!)

## Getting started / FAQ for beginners
- Which versions of which compilers are supported? gcc? clang?
- Do I have to use Meson? Is Cmake supported?
- How do I link `dxvk-native` to my own program?
- Is static linking supported?
- Are there code examples?

**Comment by Arxcis** [comment]
Please re-open if this is an interesting discussion to have.

**Comment by Joshua-Ashton** [comment]
Why did you close it? I've just been busy with other work recently.

**Comment by Arxcis** [comment]
I figured you are a busy person, and could re-open whenever you wanted to deal with it :+1:

**Comment by Arxcis** [comment]
## Use case 2
- As a `dxvk` developer, I want to compile and test `dxvk` natively on `linux`?

**Comment by caiiiycuk** [comment]
@Arxcis @Joshua-Ashton Any updates on this? Can I compile DirectX9 code on linux and run it natively without wine? Any examples. :pray:

**Comment by caiiiycuk** [comment]
I tried to compile tests but I have this error:
```
../tests/d3d9/meson.build:1:0: ERROR: Unknown variable "lib_d3d9".

```

**Comment by Joshua-Ashton** [comment]
You can, I need to get around to adding some documentation and making the tests work ootb.

**Comment by caiiiycuk** [comment]
WoW! I did it with sdl2 & dxvk-native :)

**Comment by caiiiycuk** [comment]
Is d3dx9.h also supported?

**Comment by Joshua-Ashton** [comment]
You could probably make the Wine one work with some persuasion.

**Comment by caiiiycuk** [comment]
Perimeter is also using dxvk native to build Linux version 
https://github.com/KranX/Perimeter

**Comment by q4a** [comment]
Some tutorial / FAQ for beginners is very much needed. I spent part of the day figuring out what caused the error `Failed to create surface` when calling `d3d->CreateDevice(...)`. It turned out that I just forgot to add flag `SDL_WINDOW_VULKAN`when creating SDL2 window with `SDL_CreateWindow`
